apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |
    # Настройки Redis конфигурации
    bind 0.0.0.0  # Разрешить подключение ко всем сетевым интерфейсам
    port 6379  # Порт Redis для прослушивания входящих соединений

    # Ограничение использования памяти
    maxmemory 256mb  # Максимальный объем памяти для Redis (256MB)
    maxmemory-policy allkeys-lru  # Политика вытеснения данных при нехватке памяти (LRU)

    # Сохранение данных на диск (RDB)
    save 900 1  # Создать snapshot каждые 900 секунд, если хотя бы 1 ключ был изменен
    save 300 10  # Создать snapshot каждые 300 секунд, если хотя бы 10 ключей были изменены
    save 60 10000  # Создать snapshot каждые 60 секунд, если хотя бы 10000 ключей были изменены

    # AOF (Append-Only File) для надежного сохранения данных
    appendonly yes  # Включить режим AOF для записи всех операций в файл
    appendfilename "appendonly.aof"  # Имя файла для AOF
    appendfsync everysec  # Синхронизировать данные на диск каждую секунду

    # Безопасность
    requirepass mypassword  # Установить пароль для аутентификации (замените на ваш пароль)
    protected-mode yes  # Включить защищенный режим для предотвращения несанкционированного доступа

    # Таймауты
    timeout 300  # Закрыть соединение через 300 секунд бездействия
    tcp-keepalive 300  # Интервал проверки активности TCP-соединения (в секундах)

    # Логирование
    loglevel notice  # Уровень логирования (debug, verbose, notice, warning)
    logfile ""  # Файл для записи логов (пусто для вывода в stdout)